sudo: true
dist: trusty

language: node_js 

addons:
  apt:
    packages:
      npm

before_install:
  - ./.travis/install-dependencies.sh 

script:
  - ./functional_tests/test.sh bionitio.js
  - ./.travis/unit-test.sh
