sudo: true
dist: trusty

language: node_js 
node_js: node

addons:
  apt:
    packages:
      npm

script:
  - ./functional_tests/bionitio-test.sh -p $TRAVIS_BUILD_DIR/bionitio.js -d functional_tests/test_data
  - ./.travis/unit-test.sh
